import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatDate, formatDateTime, formatHours } from './format'

/**
 * Genera y descarga un PDF de comprobante de pago al contractor (FR-10), modelo en
 * HORAS (slice 04d): un pago cubre a UN contractor bajo una factura agrupada. Sin
 * monto/moneda: el detalle es en horas.
 *
 * @param {{
 *   invoice: object,                 // factura agrupada (spInvoiceNumber, project, client, weekStart)
 *   invoiceContractor?: object,      // fila del contractor pagado (contractor, hours, supplierInvoiceNumber)
 *   payment: object,                 // el pago (paymentDate, bankMethod, transferReference, notes, backDated)
 *   generatedBy?: string,
 * }} data
 */
export function downloadPaymentReceipt({ invoice, invoiceContractor, payment, generatedBy }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const accent = [124, 58, 237] // violeta

  const ic = invoiceContractor ?? {}
  const contractor = ic.contractor ?? payment.userName ?? '—'
  const spNumber = invoice.spInvoiceNumber ?? invoice.supplierInvoiceNumber ?? '—'
  const supplierNumber = ic.supplierInvoiceNumber ?? '—'
  const hours = Number(ic.hours) || 0

  // --- Header ---
  doc.setFillColor(10, 10, 10)
  doc.rect(0, 0, pageW, 76, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('SOUTHPOINT TECH LABS', 40, 38)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(180, 180, 185)
  doc.text('Contractor payment receipt', 40, 56)

  // --- Título / nº ---
  doc.setTextColor(20, 20, 20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.text('Payment Receipt', 40, 116)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(110, 110, 115)
  doc.text(`SP invoice ${spNumber}`, 40, 134)

  // --- Tabla de detalle (en horas, sin plata) ---
  autoTable(doc, {
    startY: 156,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 6, textColor: [30, 30, 30] },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [110, 110, 115], cellWidth: 170 },
      1: { textColor: [20, 20, 20] },
    },
    body: [
      ['Contractor', contractor],
      ['SP invoice', spNumber],
      ['Supplier invoice', supplierNumber],
      ['Project', invoice.project || '—'],
      ['Week', invoice.weekStart ? formatDate(invoice.weekStart) : '—'],
      ['Hours paid', `${formatHours(hours)} h`],
      ['Payment date', formatDate(payment.paymentDate) + (payment.backDated ? '  (back-dated)' : '')],
      ['Bank / method', payment.bankMethod || '—'],
      ['Transfer reference', payment.transferReference || '—'],
      ['Notes', payment.notes || '—'],
    ],
  })

  // --- Total en horas ---
  const afterTable = doc.lastAutoTable.finalY + 24
  doc.setDrawColor(230, 230, 232)
  doc.line(40, afterTable, pageW - 40, afterTable)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(accent[0], accent[1], accent[2])
  doc.text(`TOTAL PAID:  ${formatHours(hours)} h`, 40, afterTable + 28)

  // --- Footer ---
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 155)
  doc.text(
    `Generated by ${generatedBy || '—'} on ${formatDateTime(new Date().toISOString())}`,
    40,
    doc.internal.pageSize.getHeight() - 40,
  )

  const safeNum = String(spNumber).replace(/[^\w-]/g, '_')
  const safeName = String(contractor).replace(/[^\w-]/g, '_')
  doc.save(`recibo-pago-${safeNum}-${safeName}.pdf`)
}
