import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatDate, formatDateTime, formatHours } from './format'

function fmtAmount(value) {
  return Number(value || 0).toLocaleString('es-AR', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
}

export function downloadTracePdf({ trace, collections = [], generatedBy }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const accent = [124, 58, 237]

  // Header
  doc.setFillColor(10, 10, 10)
  doc.rect(0, 0, pageW, 76, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('SOUTHPOINT TECH LABS', 40, 38)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(180, 180, 185)
  doc.text('Traceability Report', 40, 56)

  // Entry heading
  doc.setTextColor(20, 20, 20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(`Entry #${trace.timeEntryId} — ${trace.userName}`, 40, 110)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(110, 110, 115)
  doc.text(
    `${formatDate(trace.logDate)} · ${trace.hours}h · ${trace.project ?? '—'} · ${trace.client ?? '—'}`,
    40,
    128,
  )

  // Timeline table
  const body = []

  body.push([
    'Logged in Zoho',
    formatDate(trace.logDate),
    [
      `${trace.hours}h · ${trace.project ?? '—'} · ${trace.client ?? '—'}`,
      trace.task ? `Task: ${trace.task}` : null,
      trace.zohoLogId ? `Zoho ID: ${trace.zohoLogId}` : null,
    ]
      .filter(Boolean)
      .join('\n'),
  ])

  body.push([
    'Synced to App',
    trace.syncedAt ? formatDateTime(trace.syncedAt) : '—',
    trace.zohoLogId ? `Zoho log ID: ${trace.zohoLogId}` : '—',
  ])

  if (trace.invoiceId) {
    body.push([
      'Invoiced',
      formatDate(trace.invoiceDate),
      [
        trace.spInvoiceNumber ? `SP invoice: ${trace.spInvoiceNumber}` : null,
        trace.invoiceContractor ? `Contractor: ${trace.invoiceContractor}` : null,
        trace.contractorHours != null ? `${formatHours(trace.contractorHours)} h` : null,
        trace.invoicedBy ? `By: ${trace.invoicedBy}` : null,
      ]
        .filter(Boolean)
        .join('\n'),
    ])
  } else {
    body.push(['Invoiced', 'Pending', '—'])
  }

  const isCollected = trace.invoiceStatus === 'Collected' || trace.invoiceStatus === 'Paid'
  if (isCollected) {
    const collLines = [`Total collected: $${fmtAmount(trace.collectedAmount)}`]
    if (collections.length > 0) {
      collections.forEach((c) => {
        collLines.push(`${formatDate(c.collectionDate)}: $${fmtAmount(c.amountReceived)}${c.bankReference ? ` · ${c.bankReference}` : ''}`)
      })
    }
    body.push(['Collected', formatDate(trace.lastCollectionDate), collLines.join('\n')])
  } else {
    body.push(['Collected', 'Pending', '—'])
  }

  if (trace.paymentId) {
    body.push([
      'Paid to Contractor',
      formatDate(trace.paymentDate),
      [
        trace.supplierInvoiceNumber ? `Supplier invoice: ${trace.supplierInvoiceNumber}` : null,
        trace.bankMethod ? `Method: ${trace.bankMethod}` : null,
        trace.transferReference ? `Ref: ${trace.transferReference}` : null,
        trace.paidBy ? `By: ${trace.paidBy}` : null,
      ]
        .filter(Boolean)
        .join('\n'),
    ])
  } else {
    body.push(['Paid to Contractor', 'Pending', '—'])
  }

  autoTable(doc, {
    startY: 150,
    head: [['Step', 'Date', 'Details']],
    body,
    theme: 'striped',
    headStyles: { fillColor: accent, textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 7, valign: 'top' },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [110, 110, 115], cellWidth: 120 },
      1: { cellWidth: 90 },
    },
  })

  // Footer
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 155)
  doc.text(
    `Generated by ${generatedBy || '—'} on ${formatDateTime(new Date().toISOString())}`,
    40,
    doc.internal.pageSize.getHeight() - 40,
  )

  const safeName = (trace.userName ?? 'entry').replace(/\s+/g, '_')
  doc.save(`trace_${trace.timeEntryId}_${safeName}.pdf`)
}
